name: Pi Deploy Automation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # Hiermee herkent hij je Pi runner
    steps:
      - name: Update Code via Python Script
        run: |
          /usr/local/bin/puller-git https://${{ secrets.GH_TOKEN }}@github.com/IEP-The-Green-Blanket/Front-End.git --dest /home/tripp/ie-Project/Front-End

      - name: Herstart Docker Container
        run: |
          /usr/local/bin/deploy --path /home/tripp/ie-Project/Front-End
